name: java-open-chess # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Java version of chess
description: |
  Java version of chess that also supports network play

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  jchess_icon.png
title: Java Open Chess

apps:
  jchess:
    command: startjchess
parts:
  jchess:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      jchess: build/
      jchess.1: man/man1/

architectures:
  - build-on: amd64

